MyMovieApp/Controllers/CinemaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyMovieApp.Interface;
using MyMovieApp.ViewModel;

namespace MyMovieApp.Controllers
    {
    public class CinemaController : Controller
        {
        private readonly IUnitOfWork _unitOfWork;
        public CinemaController(IUnitOfWork unitOfWork)
            {
            _unitOfWork = unitOfWork;
            }

        public async Task<ActionResult> Index()
            {
            var result = await _unitOfWork.cinemaRepository.GetAll();
            return View(result);
            }


        public ActionResult Details(int id)
            {
            return View();
            }


        public ActionResult Create()
            {
            return View();
            }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CinemaViewModel cinemaViewModel)
            {
            if (!ModelState.IsValid)
                {

                return View(cinemaViewModel);
                }
            try
                {
                var result = await _unitOfWork.cinemaRepository.AddCinema(cinemaViewModel);
                if (result != null)
                    TempData["success"] = "Cinema Added successfully.";
                else
                    TempData["error"] = "Error while adding cinema.";
                return RedirectToAction(nameof(Index));
                }
            catch
                {
                return View();
                }
            }

        public async Task<ActionResult> Edit(int id)
            {
            if (id == null || id == 0)
                {
                return NotFound();
                }
            var cinema = await _unitOfWork.cinemaRepository.Get(id);

            if (cinema == null)
                {
                return NotFound();
                }
            return View(cinema);
            }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CinemaViewModel cinemaViewModel)
            {
            try
                {
                if (ModelState.IsValid)
                    {
                    var result = await _unitOfWork.cinemaRepository.UpdateCinema(cinemaViewModel);
                    if ((bool)result)
                        TempData["success"] = "Cinema updated successfully.";
                    else
                        TempData["error"] = "Error while updating movie.";
                    }
                return RedirectToAction(nameof(Index));
                }
            catch (Exception ex)
                {
                return View();
                }
            }


        [HttpDelete]
        //  [ValidateAntiForgeryToken]
        public async Task<bool> Delete(int id)
            {
            try
                {
                var result = await _unitOfWork.cinemaRepository.DeleteCinema(id);
                if ((bool)result)
                    TempData["success"] = "Cinema Deleted successfully.";
                else
                    TempData["error"] = "Error while deleting Cinema.";
                 return result;
                }
            
            catch
                {
                return false;
                }
            }
    }
    }

MyMovieApp/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyMovieApp.Interface;
using MyMovieApp.ViewModel;

namespace MyMovieApp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public MoviesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;   
        }
        public async Task<IActionResult> Index(bool? forList)
        {
            var result = await _unitOfWork.moviesRepository.GetAll();
            if(forList == true)
                return Json(result);
            else
            return View(result);

        }
        

        public async Task<ActionResult> Details(int id)
        {
            var movie = await _unitOfWork.moviesRepository.Get((int)id, "Ahmedabad");
            return View(movie);
        }

        public async Task<ActionResult> Create()
        {
            var model = await _unitOfWork.moviesRepository.GetUpsertModel();           
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MovieUpsertModel movieViewModel)
        {
            if (!ModelState.IsValid)
            {
                var model = await _unitOfWork.moviesRepository.GetUpsertModel();
                return View(model);
            }
            try
            {
                var result = await _unitOfWork.moviesRepository.AddMovie(movieViewModel);   
                if (result != null)
                    TempData["success"] = "Movie Added successfully.";
                else
                    TempData["error"] = "Error while adding movie.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var movie = await _unitOfWork.moviesRepository.Get((int)id, "Ahmedabad", true);
            var upsertModel = await _unitOfWork.moviesRepository.GetUpsertModel();
            MovieUpsertModel movieUpsertModel = new MovieUpsertModel(movie);
            movieUpsertModel.Certificates = upsertModel.Certificates;
            if (movie == null)
            {
                return NotFound();
            }
            return View(movieUpsertModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(MovieUpsertModel movieViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result =  await _unitOfWork.moviesRepository.UpdateMovie(movieViewModel);
                    if ((bool)result)
                        TempData["success"] = "Movie updated successfully.";
                    else
                        TempData["error"] = "Error while updating movie.";
                }
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex) 
            {
                return View();
            }
        }

        public async Task<ActionResult> Delete(int? id)
        {
           
            var movie = await _unitOfWork.moviesRepository.Get((int)id, "Ahmedabad");
            if (movie == null)
            {
                return NotFound();
            }
            return View( movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteMovie(int id)
        {
            try
            {
                var result = await _unitOfWork.moviesRepository.DeleteMovie(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> SeatLayout (int id)
            {
            var movie = await _unitOfWork.moviesRepository.Get((int)id, "Ahmedabad");
            if (movie == null)
                {
                return NotFound();
                }
            return View(movie);
            }
    }
}

MyMovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyMovie</title>
    <base href="~/" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyMovieApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="icon" href="~/img/favicon2.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <a class="navbar-brand" style="font-family:'Audiowide';" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.svg" alt="MyMovie" style="height: 40px;" /> MyMovie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinema</a>
                        </li>
                        <li class="nav-item">
                           <partial name="_Order" />
                        </li>
                        <li class="nav-item">
                           @*  <partial name="_MovieList" /> *@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class=" text-muted mt-5">
        <div class="container">
            <div class="text-center ">
                <i  class="bi bi-twitter fs-3 px-3"></i>
                <i class="bi bi-facebook fs-3 px-3"></i>
                <i class="bi bi-instagram fs-3 px-3"></i>
            </div>
            <div class="text-center">
             Copyright &copy; 2024 - MovieRockerz.Pvt.Ltd. All rights reserved. <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="_framework/blazor.server.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyMovieApp/Views/Shared/_MovieList.cshtml
<style>
    .tooltips {
        position: relative;
        display: inline-block;
    }

         .tooltiptext {
            background: white;
            display: flex;
            visibility: hidden;
            border: 2px solid #eee;
            text-align: center;
            border-radius: 6px;
            padding: 5px 0;
            position: absolute;
            z-index: 1;
            bottom: -425%;
            left: 50%;
            transform: translateX(-50%);
            opacity: 0;
            transition: opacity 0.3s;
        }

            

        .tooltips:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
</style>
<div class="timeBlock tooltips">

<a class="nav-link text-dark" id="showMovieList">MovieList</a>
    <div class="tooltiptext">
        <div id="movieList">
    </div>
</div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){

        $('#showMovieList').on('mouseenter',function(){
            debugger;
            $.ajax({
            url : 'Movies/Index?forList=true',
            type : 'GET',
                success: function (data) {
                    console.log(data);
                    data.forEach(function (movie) {
                        var listItem = $('<div></div>').text(movie.title);                          
                            $('#movieList').append(listItem);
                    })
                },
                error: function (error) {

                }
            })
        })
    })
</script>

MyMovieApp/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@if (TempData["success"] != null)
    {
    <script type="text/javascript">

        toastr.success('@TempData["success"]');
        setTimeout(function () {
        @{
            TempData["success"] = null;
        }
        }, 5000);
    </script>
    @*<span class="text-success">@TempData["success"]</span>*@
    }
@if (TempData["error"] != null)
    {
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
    TempData["error"] = null;
    @*<span class="text-danger">@TempData["success"]</span>*@
    }

MyMovieApp/Views/Shared/_Order.cshtml
<a type="button" class="nav-link text-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">Order</a>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="border-bottom:none;">
                <img src="~/img/login.png" alt="Login" style="height: 40px;" />
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Login with mobile number</label>
                        <input type="text" class="form-control" id="recipient-name" placeholder="Enter mobile number">
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Login with Email</label>
                        <input type="text" class="form-control" id="recipient-name" placeholder="Enter your email">
                    </div>
                </form>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-primary">Get OTP</button>
            </div>
        </div>
    </div>
</div>